### ISSUE TITLE
Add provision for showing the recordings across all the subdomains.

### ISSUE THREAD

**Issue by yureshwar** [Digital-Assistant/Digital_Assistant_Client#449]
When we record we should provide a provision to enable the recording to be visible for all the subdomains of the top level domain.

**Comment by yureshwar** [comment]
For now we are modifying based on the flag provided by the developer

enableForAllDomains: true

and we are extracting the TLD from the given package which is more popular and fast enough in retrieving the TLD.
https://www.npmjs.com/package/parse-domain?activeTab=readme

**Comment by kcramakrishna** [comment]
Elastic seems to have decent support for domains and sub-domains.
https://www.elastic.co/guide/en/elasticsearch/reference/8.9/uri-parts-processor.html 
https://www.elastic.co/guide/en/elasticsearch/reference/current/registered-domain-processor.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/registered-domain-processor.html

Ideally, we want elastic to do all the hardwork of splitting and/or storing of domains and subdomains. 
User passes an appropriate flag during recording. We can check the flag and accordingly instruct quarkus+elastic to take care of the request i.e. both during indexing and during retrieval. 
The only changes are probably  to store the flag in DB as a separate coloumn. (since this is permanent info input to quarkus).
We can also enable users to specify a list of individual subdomains where this is valid. The default is wildcard '*'

Elastic search retrieval can be based on '*' or list of subdomains.

**Comment by kcramakrishna** [comment]
Docs on how to handle index pipelines and ingest processors.
https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html#add-pipeline-to-indexing-request

Quarkus + Elastic Tutorial:
https://quarkus.io/guides/hibernate-search-orm-elasticsearch

RegisteredDomain Processor and Java
https://artifacts.elastic.co/javadoc/co/elastic/clients/elasticsearch-java/8.9.0/co/elastic/clients/elasticsearch/ingest/package-summary.html
https://github.com/elastic/elasticsearch/blob/main/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/RegisteredDomainProcessor.java
https://artifacts.elastic.co/javadoc/co/elastic/clients/elasticsearch-java/8.9.0/co/elastic/clients/elasticsearch/ingest/ElasticsearchIngestClient.html

Did not find anythings specific to Quarkus but I suppose this can be searched for within Quarkus forums.

Advanced custom pipelines using GROK: (generic solution unrelated to current issue)
https://www.elastic.co/blog/structuring-elasticsearch-data-with-grok-on-ingest-for-faster-analytics
